### ISSUE TITLE
UniCode/utf8 in compound names and synonyms

### ISSUE THREAD

**Issue by smoretti** [oolonek/ISDB#5]
Hi
do you plan to fix UniCode/utf8 in compound names and synonyms?

Best

**Comment by bjonnh** [comment]
Do you have examples of problematic entries?

**Comment by smoretti** [comment]
e.g. PMA_225439 Hederagenin-3-O-??-L-rhamnopyranosyl-(1‘Â∆2)-??-L-arabinopyranosyl-28-O-3-acetyl-??-D-xylopyranosyl-(1‘Â∆6)-??-D-glucopyranoside

Or PMA_207055	?ˆ7-Dehydrosophoramine

**‘Â∆** should be *->* I guess.
**?ˆ** should be *delta* I guess.

I have 846 compound names with UniCode.

Don't know what **??** is supposed to replace, but it is not seen as UniCode.

**Comment by oolonek** [comment]
Recommended metadata for ISDB should now preferably be fetched at https://zenodo.org/record/6378204
