### ISSUE TITLE
Message: 'ERROR opening ! ERROR loading model from  (in MS2ScoringModel::LoadModel())'

### ISSUE THREAD

**Issue by naydja** [oolonek/ISDB#6]
Hello, guys! 

I'm trying to use the dereplication tool described in the research paper 'Integration of Molecular Networking and MS-MS Fragmentation for Natural Products Dereplication' , but it isn't working with my data... I can't generate any results from the workflow described in the methodology. 

I noticed that the data in the .out table from older versions of GNPS (as described in the paper) is organized differently in the .clustersummary table that is generated in the current version and I even tried to edit it manually to let the columns all in the same order found previously in the .out file, but it didn't work out.

The .log file generated points to the following message: 
**'ERROR opening!
ERROR loading model from  (in MS2ScoringModel::LoadModel())'**

I did not understand what this error means ... Could someone help me?

I am attaching the files I used for the analysis and the log file.
[GNPS.zip](https://github.com/oolonek/ISDB/files/3831799/GNPS.zip)
[out_teste4.zip](https://github.com/oolonek/ISDB/files/3831800/out_teste4.zip)

Regards,
Naydja

**Comment by oolonek** [comment]
Hello Naydja,

I will try to have a look at the files your sent (are these the one causing problem ? ). Ideally could you provide a direct link to the results of your GNPS job please ?

Could you detail at which step do you get the message 

**'ERROR opening!
ERROR loading model from (in MS2ScoringModel::LoadModel())'**

Best,

PM

**Comment by oolonek** [comment]
@naydja 

I just tested using your files (in the GNPS.zip folder as input and didn't get any message error).

The reason why you didn't have results is for a strange bug (maybe not a bug actually) that you can sometimes observe in GNPS outputs. In the .mgf headers you have ACTIVATION=HCD, you need to replace all these occurences by ACTIVATION=CID and ...voila ! It works !

Here are your results and the modified .mgf for info 
[teste_cid_mod_results.zip](https://github.com/oolonek/ISDB/files/3841848/teste_cid_mod_results.zip)

Cheers,

PM

**Comment by naydja** [comment]
Hey! Thanks for your help! I appreciated that!
